# Generated by Django 5.2.3 on 2025-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_alter_employee_create_time_alter_employee_depart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Num_manage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numbers", models.CharField(max_length=11, verbose_name="电话号码")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "普通"), (2, "稀有"), (3, "超稀有")],
                        default=1,
                        verbose_name="稀有度",
                    ),
                ),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[(1, "已占用"), (2, "未占用")], default=2, verbose_name="占用状态"
                    ),
                ),
            ],
        ),
    ]
