# Generated by Django 5.2.3 on 2025-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_num_manage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="姓名")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
            ],
        ),
    ]
