# Generated by Django 5.2.3 on 2025-06-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "紧急"), (2, "重要"), (3, "临时")],
                        default=2,
                        verbose_name="级别",
                    ),
                ),
                ("detail", models.TextField(verbose_name="详细信息")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="负责人",
                    ),
                ),
            ],
        ),
    ]
